package(default_visibility = ['//visibility:public'])

load("//thirdparty/protobuf:protobuf.bzl", 'cc_proto_library')

cc_proto_library(
    name = 'sstable_service_proto',
    srcs = ['sstable_service.proto'],
)
