/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hbase1_CONSTANTS_H
#define hbase1_CONSTANTS_H

#include "mobvoi/base/hbase1_types.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

class hbase1Constants {
 public:
  hbase1Constants();

};

extern const hbase1Constants g_hbase1_constants;

}}}} // namespace

#endif
